"""inititalmigration

Revision ID: 47988ebfb4ed
Revises: b6d512929e9a
Create Date: 2025-04-06 18:06:53.235650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47988ebfb4ed'
down_revision = 'b6d512929e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brothers', schema=None) as batch_op:
        batch_op.drop_index('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brothers', schema=None) as batch_op:
        batch_op.create_index('password', ['password'], unique=True)

    # ### end Alembic commands ###
