"""inititalmigration

Revision ID: 8afa8b922263
Revises: 6063ea850c85
Create Date: 2025-04-06 17:00:04.853108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afa8b922263'
down_revision = '6063ea850c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brothers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brothers', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
